sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: a159875321
  redis:
    host: localhost
    port: 6379
    password: ""
  wechat:
    appid: wxcf5a7445640af233
    secret: c2b76412fbc34ff5caeb50147e942a65
